# HIAPP BASE image
# 2017-07-10

FROM debian:stretch-20170620
MAINTAINER Kai Käpölä <kai.kapola@iki.fi>

RUN apt-get update
RUN apt-get install -y python3.5 wget

#Set python 3.5 as default version 
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.5 1

#Install pip for Python
RUN cd /var/tmp
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py

#Install Bottle for Python
RUN pip install bottle

#Install Gunicorn web-server for Bottle
RUN pip install gunicorn

#Install Gevent for web-server
RUN pip install gevent

#Install SQLite-plugin for Bottle
RUN pip install bottle-sqlite

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*