CREATE TABLE location (id TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, status INTEGER NOT NULL DEFAULT 0, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE box (id TEXT PRIMARY KEY NOT NULL, location_id TEXT NOT NULL, name TEXT NOT NULL, status INTEGER NOT NULL DEFAULT 0, occupancy INTEGER NOT NULL, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY(location_id) REFERENCES location(id));
CREATE TABLE item (id TEXT PRIMARY KEY NOT NULL, box_id TEXT NOT NULL, year INTEGER NOT NULL, number INTEGER NOT NULL, name TEXT NOT NULL, status INTEGER NOT NULL DEFAULT 0, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY(box_id) REFERENCES box(id));
CREATE TABLE picture (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, picture BLOB NOT NULL, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE status (object TEXT NOT NULL, code INTEGER NOT NULL, text TEXT NOT NULL);
